### ISSUE TITLE
Update today - temperature and humidity is now wrong

### ISSUE THREAD

**Issue by benoitdansereau** [ckoutavas/MMM-DHT#1]
Hi,

I had a message to update the module so I went ahead.  Now, the temperature reads 42C where it was reading around 23C before the update.  The humidity is also quite low, 23.8.

I'm thinking that they were inadvertently inverted.

**Comment by ckoutavas** [comment]
Thank you, I will take a look

**Comment by ckoutavas** [comment]
I believe I have corrected the issue. Yesterday I mistakenly inverted the temperature and humidity arguments.

**Comment by benoitdansereau** [comment]
Thank you, problem solved!
That was fast ;)
